### ISSUE TITLE
How to add arguments to bibtex when building using LaTeXing?

### ISSUE THREAD

**Issue by RobTrifiletti** [LaTeXing/LaTeXing#100]
Hi!

I’ve tried everything in order to pass arguments to bibtex using latexing, but nothing has worked for me. What I would like to do is to pass the argument -min-crossrefs=1000 to bibtex when compiling my pdf file.

I have tried accessing LaTeX.sublime-build (using the extended settings from within sublime text 3) but this seems to be read only. I have tried adding all kinds of variations of quick builds to LaTeXing.sublime-settings, but it has no effect. I have a feeling I’m missing something obvious, but for the god of me I cannot see what it is. Can you guide me through how I add arguments to subroutines (e.g. bibtex in this case) when running the cmd + b build system LaTeXing provides?

**Comment by csch0** [comment]
Since LaTeXing is using latexmk to build the pdf you have most likely to adjust the latexmkrc file accordingly (http://docs.latexing.com/stable/tutorials/extend-latexmk-with-latexing.html).

If you just want it for the single bibtex you can clearly adjust the LaTeX.sublime-build. Using the http://docs.latexing.com/stable/settings.html#additional-build-arguments settings for the general call of latexmk is also an option but not sure if they will be passed though bibtex.

Hope this will guide you into the correct direction.

**Comment by RobTrifiletti** [comment]
Thanks! Adding the latexmkrc with the line
$bibtex = 'bibtex --min-crossrefs=1000';
did the trick :)

**Comment by csch0** [comment]
You are welcome.
