### ISSUE TITLE
LaTeXing Ubuntu 1.2.8 Unable to quick build

### ISSUE THREAD

**Issue by sdrobert** [LaTeXing/LaTeXing#109]
Pressing Ctrl+B does not build and gives the console error:

Unable to find target command: ltx_default_compiler

EDIT: it seems ltx_fill no longer works either.

Thanks,
Sean

**Comment by csch0** [comment]
I am sure this an installation issue, do you use the latest version of package control which is required? Perhaps try to remove and reinstall LaTeXing.

If not helping please restart Sublime Text and post your console output.

**Comment by sdrobert** [comment]
Ah, yes, that worked. Sorry and thanks.

**Comment by csch0** [comment]
Thanks for the feedback :)

**Comment by escherpf** [comment]
I'm having a problem getting 1.2.8 and 1.2.9 to work on my work computer (i.e., Windows OS behind a firewall). I am doing an manual install of LaTeXing (Package Control installs do not work behind the firewall).  
I had a good deal of difficulty getting the new version of LaTeXing to work on my home computer, but doing a clean re-install of ST3, and multiple re-starts, finally did the trick. The same procedure is not doing the trick at work, however, so I'm wondering if there is something new about 1.2.8/9 that might be preventing it from working behind a firewall. The odd thing is that the only LaTeXing options that are not grayed out (on the menus) after installation are the settings files. It is not recognized as a build system (although the syntax file is recognized). I have made sure that Package Control is up-to-date, but as I mentioned I am not able to install LaTeXing via Package Control, only via manual download (that is the other part of the procedure that worked at home that I am unable to replicate at work).
Finally, I might add that an older version of LaTeXing (1.2.4) works just fine on my work computer.

**Comment by csch0** [comment]
Did you set a proxy server in package control?

**Comment by escherpf** [comment]
I do not. And I am ashamed to say that I am not at all familiar with how to configure these settings.

**Comment by csch0** [comment]
It changed internally since LaTeXing is now the request library for the mendeley access.

So whats missing on work? Do you get any error?

**Comment by escherpf** [comment]
Ah, it might be that the new Package Control dependencies are not installing (e.g., requests_oauthlib):

reloading plugin LaTeXing.LaTeXing
Traceback (most recent call last):
  File "D:\Sublime Text 3075\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Sublime Text 3075\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in D:\Sublime Text 3075\Data\Installed Packages\LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 16, in <module>
  File "/Development/latexing/cache.py", line 19, in <module>
  File "/Development/latexing/api/mendeley.py", line 9, in <module>
ImportError: No module named 'requests_oauthlib'
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 4 missing dependencies
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. (errno 12045) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, requests, is not available
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, requests-oauthlib, is not available
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, oauthlib, is not available
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-03-10 15:00:27, next run at 2015-03-10 16:00:27 or after

**Comment by escherpf** [comment]
Are the new package control dependencies critical for the new version of LaTeXing (i.e., for it to work at all, not just for the functionality of the Mendeley connection)?

**Comment by csch0** [comment]
Yes they are required, but just 3, and you can see even one dependency from package control (or any other package) cannot be installed. I think it's an issue with a proxy server but hard to tell from here.

I think this needs to be fixed since dependencies are a very nice feature once working. :) makes developing much easier, perhaps just a small issue on package control.

**Comment by levi-ee** [comment]
After the installation of one missing dependency :
```
Package Control: Installing 1 missing dependency
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
Package Control: Linux SSL: unloading http module so ssl will be available
Package Control: Linux SSL: unloading urllib module so ssl will be available
Package Control: Installed missing dependency ssl-linux
```

I have the error :
`Unable to find target command: ltx_default_compiler`
