### ISSUE TITLE
Is this still under active development?

### ISSUE THREAD

**Issue by aeonstone** [LaTeXing/LaTeXing#216]
Sorry if I am being rude, but I'm just wondering if LaTeXing is still being worked on. It seems like its been a year since anything has really come out. I mean LaTeXing.com still doesn't reflect that the latest version is 1.2.18.

I'm not saying we are entitled to continued development and support. I have certainly gotten my moneys worth already, but it would be nice to know if there is a continued future here.

Thanks,

Jared

**Comment by csch0** [comment]
Hello, yes I agree the website is a bit sloppy witting updated but everything is up to date in the changelog inside LaTeXing itself.

Currently I am working on an update of the website, so clear yes the development is still active even if slower than in past because the majority of the features are working without a problem. Which is also a very good thing :)

**Comment by aeonstone** [comment]
Fantastic! Thanks for the reply. I feel bad for being so slow in replying to you! Keep being awesome.
